version: "3"
services:
  lb:
    image: haproxy:2.6.6-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./lb:/usr/local/etc/haproxy
    healthcheck:
      test: ["CMD", "wget", "-nv","-t1", "--spider", "http://localhost:8080/healthz"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 3s
    depends_on:
      ws1:
        condition: service_healthy
      ws2:
        condition: service_healthy
  ws1:
    build:
      context: ./ws
      dockerfile: Dockerfile
    image: somkiat/ws
    healthcheck:
      test: ["CMD", "wget", "-nv","-t1", "--spider", "http://localhost:8080/healthz"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 3s
    depends_on:
      redis:
        condition: service_healthy
  ws2:
    image: somkiat/ws
    healthcheck:
      test: ["CMD", "wget", "-nv","-t1", "--spider", "http://localhost:8080/healthz"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 3s
    depends_on:
      redis:
        condition: service_healthy
  redis:
    image: redis:7.0.5
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 3s